// Daily presale trivia. Every question has an explanation and a source shown after answering.
// `answerIndex` points at the correct option before shuffling; options are shuffled per fan in streak.ts.
// Facts marked `// VERIFY` should be double-checked before presenting (see README).
import type { ArtistId, TriviaQuestion } from './types'

type Q = Omit<TriviaQuestion, 'artistId' | 'id'>

const wiki = (article: string) => `Wikipedia: ${article}`

const taylorSwift: Q[] = [
  { question: 'What was Taylor Swift\'s debut single?', options: ['"Tim McGraw"', '"Our Song"', '"Teardrops on My Guitar"', '"Love Story"'], answerIndex: 0, explanation: '"Tim McGraw" came out in 2006, when she was 16.', source: wiki('Tim McGraw (song)') },
  { question: 'In which year did Taylor Swift release her first album?', options: ['2004', '2006', '2008', '2010'], answerIndex: 1, explanation: 'Her self-titled debut album came out in October 2006.', source: wiki('Taylor Swift (album)') },
  { question: '"Love Story" is from which album?', options: ['Speak Now', 'Red', 'Fearless', '1989'], answerIndex: 2, explanation: '"Love Story" was the lead single from Fearless (2008).', source: wiki('Love Story (Taylor Swift song)') },
  { question: 'Which album won Taylor Swift her first Grammy for Album of the Year?', options: ['Fearless', '1989', 'Red', 'Speak Now'], answerIndex: 0, explanation: 'Fearless won Album of the Year at the 2010 Grammys.', source: wiki('Fearless (Taylor Swift album)') },
  { question: 'How old was Taylor Swift when she first won Album of the Year?', options: ['18', '20', '23', '25'], answerIndex: 1, explanation: 'She was 20, the youngest winner of the award at the time.', source: wiki('52nd Annual Grammy Awards') },
  { question: 'How many times has Taylor Swift won the Grammy for Album of the Year?', options: ['2', '3', '4', '5'], answerIndex: 2, explanation: 'Fearless, 1989, Folklore and Midnights: a record four wins.', source: wiki('Grammy Award for Album of the Year') },
  { question: '"Shake It Off" was the lead single from which album?', options: ['Red', 'Reputation', 'Lover', '1989'], answerIndex: 3, explanation: '"Shake It Off" launched 1989 in 2014.', source: wiki('Shake It Off') },
  { question: 'The album 1989 is named after what?', options: ['Her birth year', 'Her first concert', 'A film', 'A street address'], answerIndex: 0, explanation: 'Taylor Swift was born in 1989.', source: wiki('1989 (Taylor Swift album)') },
  { question: 'Taylor Swift grew up on a Christmas tree farm in which US state?', options: ['Tennessee', 'Pennsylvania', 'Ohio', 'New York'], answerIndex: 1, explanation: 'She grew up in Pennsylvania before moving to the Nashville area.', source: wiki('Taylor Swift') },
  { question: 'Which city did Taylor Swift move near as a teenager to pursue country music?', options: ['Austin', 'Memphis', 'Nashville', 'Atlanta'], answerIndex: 2, explanation: 'Her family moved to Hendersonville, near Nashville.', source: wiki('Taylor Swift') },
  { question: 'Which song gave Taylor Swift her first Billboard Hot 100 number one?', options: ['"Love Story"', '"We Are Never Ever Getting Back Together"', '"Shake It Off"', '"Blank Space"'], answerIndex: 1, explanation: '"We Are Never Ever Getting Back Together" (2012) was her first Hot 100 number one.', source: wiki('We Are Never Ever Getting Back Together') },
  { question: 'Which album did Taylor Swift write entirely by herself?', options: ['Speak Now', 'Fearless', 'Red', 'Lover'], answerIndex: 0, explanation: 'She wrote every song on Speak Now (2010) without co-writers.', source: wiki('Speak Now') },
  { question: 'Which 2020 album did Taylor Swift announce only hours before releasing it?', options: ['Lover', 'Folklore', 'Midnights', 'Reputation'], answerIndex: 1, explanation: 'Folklore was announced and released on the same day in July 2020.', source: wiki('Folklore (Taylor Swift album)') },
  { question: 'What is the "sister album" to Folklore?', options: ['Evermore', 'Lover', 'Midnights', 'Red'], answerIndex: 0, explanation: 'Evermore followed in December 2020 as a companion to Folklore.', source: wiki('Evermore (Taylor Swift album)') },
  { question: 'What label do Taylor Swift\'s re-recorded albums carry?', options: ['(Deluxe)', '(Remastered)', '(Taylor\'s Version)', '(Encore)'], answerIndex: 2, explanation: 'Re-recordings are released as "(Taylor\'s Version)".', source: wiki('Taylor Swift masters dispute') },
  { question: 'Which album was the first to be re-recorded as "Taylor\'s Version"?', options: ['Red', 'Fearless', 'Speak Now', '1989'], answerIndex: 1, explanation: 'Fearless (Taylor\'s Version) came out in April 2021.', source: wiki("Fearless (Taylor's Version)") },
  { question: 'Which song became the longest ever to reach number one on the Billboard Hot 100?', options: ['"All Too Well (10 Minute Version)"', '"Cruel Summer"', '"Anti-Hero"', '"Cardigan"'], answerIndex: 0, explanation: 'The 10-minute "All Too Well" topped the Hot 100 in November 2021.', source: wiki('All Too Well') },
  { question: 'What was the lead single from Midnights?', options: ['"Lavender Haze"', '"Karma"', '"Anti-Hero"', '"Bejeweled"'], answerIndex: 2, explanation: '"Anti-Hero" led Midnights (2022) and debuted at number one.', source: wiki('Anti-Hero (song)') },
  { question: 'In which city did The Eras Tour open in March 2023?', options: ['Los Angeles', 'Glendale, Arizona', 'Nashville', 'New York'], answerIndex: 1, explanation: 'The tour opened at State Farm Stadium in Glendale on 17 March 2023.', source: wiki('The Eras Tour') },
  { question: 'The Eras Tour was the first tour to gross more than what?', options: ['$500 million', '$750 million', '$1 billion', '$5 billion'], answerIndex: 2, explanation: 'It passed $1 billion in 2023 and became the highest-grossing tour of all time.', source: wiki('The Eras Tour') },
  { question: 'Which album did Taylor Swift announce in her Grammys acceptance speech in February 2024?', options: ['Midnights', 'The Tortured Poets Department', 'Evermore', '1989 (Taylor\'s Version)'], answerIndex: 1, explanation: 'She announced The Tortured Poets Department while accepting a Grammy.', source: wiki('The Tortured Poets Department') },
  { question: 'What are Taylor Swift\'s fans called?', options: ['Swifties', 'Tay-Tays', 'Erasers', 'Lovers'], answerIndex: 0, explanation: 'Her fan base is known as Swifties.', source: wiki('Swifties') },
  { question: 'What is Taylor Swift\'s well-known lucky number?', options: ['7', '13', '22', '89'], answerIndex: 1, explanation: 'She has often said 13 is her lucky number.', source: wiki('Taylor Swift') },
  { question: '"Look What You Made Me Do" was the lead single from which album?', options: ['Reputation', 'Lover', '1989', 'Red'], answerIndex: 0, explanation: 'It launched Reputation in 2017.', source: wiki('Look What You Made Me Do') },
  { question: 'Which 2019 song became a number one hit in 2023?', options: ['"Lover"', '"ME!"', '"Cruel Summer"', '"The Man"'], answerIndex: 2, explanation: '"Cruel Summer" from Lover reached number one on the Hot 100 in 2023, boosted by the Eras Tour.', source: wiki('Cruel Summer (Taylor Swift song)') },
  { question: 'In which two Australian cities did The Eras Tour play in February 2024?', options: ['Sydney and Brisbane', 'Melbourne and Sydney', 'Perth and Melbourne', 'Adelaide and Sydney'], answerIndex: 1, explanation: 'The Australian leg played the MCG in Melbourne and Accor Stadium in Sydney.', source: wiki('The Eras Tour') },
  { question: 'What is Taylor Swift\'s middle name?', options: ['Alison', 'Marie', 'Grace', 'Elizabeth'], answerIndex: 0, explanation: 'Her full name is Taylor Alison Swift.', source: wiki('Taylor Swift') },
  { question: 'Which of these is the name of one of Taylor Swift\'s cats?', options: ['Olivia Benson', 'Rachel Green', 'Leslie Knope', 'Buffy Summers'], answerIndex: 0, explanation: 'Her cats are Meredith Grey, Olivia Benson and Benjamin Button.', source: wiki('Taylor Swift') },
  { question: '"ME!" featuring Brendon Urie was the lead single from which album?', options: ['Lover', 'Folklore', 'Reputation', '1989'], answerIndex: 0, explanation: '"ME!" launched Lover in 2019.', source: wiki('Me! (Taylor Swift song)') },
  { question: 'In which year was Red first released?', options: ['2010', '2012', '2014', '2016'], answerIndex: 1, explanation: 'Red came out in October 2012.', source: wiki('Red (Taylor Swift album)') },
  { question: 'Which 2023 concert film became the highest-grossing concert film ever?', options: ['Taylor Swift: The Eras Tour', 'Reputation Stadium Tour', 'Miss Americana', 'Folklore: The Long Pond Studio Sessions'], answerIndex: 0, explanation: 'The Eras Tour film became the highest-grossing concert film of all time.', source: wiki('Taylor Swift: The Eras Tour (film)') },
  { question: 'Who co-produced Folklore with Jack Antonoff?', options: ['Max Martin', 'Aaron Dessner', 'Finneas', 'Shellback'], answerIndex: 1, explanation: 'Aaron Dessner of The National co-produced much of Folklore.', source: wiki('Folklore (Taylor Swift album)') },
]

const bts: Q[] = [
  { question: 'In which year did BTS debut?', options: ['2011', '2013', '2015', '2017'], answerIndex: 1, explanation: 'BTS debuted on 13 June 2013.', source: wiki('BTS') },
  { question: 'What was BTS\'s debut single?', options: ['"No More Dream"', '"I Need U"', '"Boy in Luv"', '"Danger"'], answerIndex: 0, explanation: 'They debuted with "No More Dream", a track about the pressure on young people.', source: wiki('No More Dream') },
  { question: 'What is the name of the BTS fandom?', options: ['BLINK', 'CARAT', 'ARMY', 'ONCE'], answerIndex: 2, explanation: 'ARMY stands for Adorable Representative M.C. for Youth.', source: wiki('BTS') },
  { question: 'Which BTS single was their first number one on the Billboard Hot 100?', options: ['"Dynamite"', '"Fake Love"', '"Boy With Luv"', '"DNA"'], answerIndex: 0, explanation: '"Dynamite" reached number one in September 2020.', source: wiki('Dynamite (BTS song)') },
  { question: '"DNA" comes from which album?', options: ['Love Yourself: Her', 'Map of the Soul: 7', 'Wings', 'BE'], answerIndex: 0, explanation: '"DNA" is on Love Yourself: Her (2017).', source: wiki('DNA (BTS song)') },
  { question: '"DNA" was BTS\'s first song to do what?', options: ['Win a Grammy', 'Enter the Billboard Hot 100', 'Top the UK chart', 'Reach a billion streams'], answerIndex: 1, explanation: '"DNA" was their first entry on the Billboard Hot 100.', source: wiki('DNA (BTS song)') },
  { question: 'How many members are in BTS?', options: ['5', '6', '7', '9'], answerIndex: 2, explanation: 'BTS has seven members.', source: wiki('BTS') },
  { question: 'Who is the leader of BTS?', options: ['Jin', 'RM', 'Suga', 'J-Hope'], answerIndex: 1, explanation: 'RM is the group\'s leader.', source: wiki('RM (rapper)') },
  { question: 'Which of these is NOT a member of BTS?', options: ['Jimin', 'V', 'Jungkook', 'Taemin'], answerIndex: 3, explanation: 'The members are RM, Jin, Suga, J-Hope, Jimin, V and Jungkook. Taemin is from SHINee.', source: wiki('BTS') },
  { question: 'Who is the youngest member of BTS?', options: ['Jungkook', 'Jimin', 'V', 'J-Hope'], answerIndex: 0, explanation: 'Jungkook, born in 1997, is the youngest ("maknae").', source: wiki('Jungkook') },
  { question: 'Who is the oldest member of BTS?', options: ['Suga', 'RM', 'Jin', 'J-Hope'], answerIndex: 2, explanation: 'Jin, born in 1992, is the oldest member.', source: wiki('Jin (singer)') },
  { question: 'What does BTS stand for in Korean?', options: ['Bangtan Sonyeondan', 'Beyond The Scene only', 'Big Time Seoul', 'Bulletproof Team Seoul'], answerIndex: 0, explanation: 'Bangtan Sonyeondan means "Bulletproof Boy Scouts". "Beyond the Scene" was added later as an English meaning.', source: wiki('BTS') },
  { question: 'Which agency launched BTS?', options: ['SM Entertainment', 'JYP Entertainment', 'Big Hit Entertainment', 'YG Entertainment'], answerIndex: 2, explanation: 'BTS debuted under Big Hit Entertainment, now part of HYBE.', source: wiki('Hybe Corporation') },
  { question: 'In 2018, RM gave a speech at which organisation?', options: ['The United Nations', 'The European Parliament', 'The White House', 'UNESCO in Paris'], answerIndex: 0, explanation: 'RM spoke at the UN General Assembly for UNICEF\'s Generation Unlimited launch.', source: wiki('BTS') },
  { question: 'Which 2021 English single spent 10 weeks at number one on the Hot 100?', options: ['"Butter"', '"Dynamite"', '"Permission to Dance"', '"My Universe"'], answerIndex: 0, explanation: '"Butter" spent 10 weeks at number one.', source: wiki('Butter (song)') },
  { question: 'Which BTS song replaced "Butter" at number one in July 2021?', options: ['"Life Goes On"', '"Permission to Dance"', '"Dynamite"', '"Yet to Come"'], answerIndex: 1, explanation: '"Permission to Dance" took over the top spot from "Butter".', source: wiki('Permission to Dance') },
  { question: 'Who featured on "Boy With Luv"?', options: ['Halsey', 'Ed Sheeran', 'Megan Thee Stallion', 'Lauv'], answerIndex: 0, explanation: '"Boy With Luv" (2019) features Halsey.', source: wiki('Boy with Luv') },
  { question: 'BTS\'s first Grammy nomination was in which category?', options: ['Best New Artist', 'Best Pop Duo/Group Performance', 'Record of the Year', 'Best Music Video'], answerIndex: 1, explanation: '"Dynamite" was nominated for Best Pop Duo/Group Performance at the 2021 Grammys.', source: wiki('63rd Annual Grammy Awards') },
  { question: '"Fake Love" was the lead single from which album?', options: ['Love Yourself: Tear', 'Wings', 'BE', 'Proof'], answerIndex: 0, explanation: '"Fake Love" led Love Yourself: Tear (2018).', source: wiki('Fake Love (song)') },
  { question: 'Love Yourself: Tear was the first K-pop album to do what?', options: ['Top the Billboard 200', 'Win a Grammy', 'Go diamond', 'Chart in 100 countries'], answerIndex: 0, explanation: 'It was the first K-pop album to reach number one on the Billboard 200.', source: wiki('Love Yourself: Tear') },
  { question: '"Blood Sweat & Tears" is from which album?', options: ['Wings', 'BE', 'Map of the Soul: Persona', 'Dark & Wild'], answerIndex: 0, explanation: '"Blood Sweat & Tears" was the lead single from Wings (2016).', source: wiki('Blood Sweat & Tears (song)') },
  { question: '"Spring Day" was released on which album?', options: ['You Never Walk Alone', 'Love Yourself: Answer', 'BE', 'Skool Luv Affair'], answerIndex: 0, explanation: '"Spring Day" is on You Never Walk Alone (2017), the repackage of Wings.', source: wiki('Spring Day') },
  // VERIFY: Wembley shows were the Speak Yourself extension of this tour.
  { question: 'In 2019 BTS became the first Korean act to headline which London stadium?', options: ['Wembley Stadium', 'Twickenham', 'The O2 Arena', 'Emirates Stadium'], answerIndex: 0, explanation: 'They played two sold-out shows at Wembley in June 2019.', source: wiki('Love Yourself World Tour') },
  { question: 'Which BTS song was the first mostly Korean-language song to debut at number one on the Hot 100?', options: ['"Life Goes On"', '"Idol"', '"On"', '"Spring Day"'], answerIndex: 0, explanation: '"Life Goes On" from BE debuted at number one in 2020.', source: wiki('Life Goes On (BTS song)') },
  { question: 'BTS collaborated with which band on "My Universe"?', options: ['Coldplay', 'Imagine Dragons', 'Maroon 5', 'The Chainsmokers'], answerIndex: 0, explanation: '"My Universe" (2021) with Coldplay reached number one on the Hot 100.', source: wiki('My Universe (song)') },
  { question: 'Which colour is linked to BTS through the phrase "I purple you"?', options: ['Purple', 'Blue', 'Gold', 'Pink'], answerIndex: 0, explanation: 'V coined "I purple you", meaning "I will trust and love you for a long time".', source: wiki('BTS') },
  { question: 'Which 2022 anthology album includes "Yet to Come"?', options: ['Proof', 'BE', 'Butter', 'Map of the Soul: 7'], answerIndex: 0, explanation: 'Proof (2022) marked nine years of BTS and led with "Yet to Come".', source: wiki('Proof (album)') },
  { question: 'Which BTS member was the first to begin military service, in December 2022?', options: ['Jin', 'Suga', 'RM', 'Jungkook'], answerIndex: 0, explanation: 'Jin enlisted first, in December 2022.', source: wiki('Jin (singer)') },
  { question: 'Jungkook\'s solo single "Seven" features which artist?', options: ['Latto', 'Halsey', 'Lizzo', 'Doja Cat'], answerIndex: 0, explanation: '"Seven" (2023) featuring Latto debuted at number one on the Hot 100.', source: wiki('Seven (Jungkook song)') },
  { question: 'Which BTS member was the first Korean soloist to top the Hot 100, with "Like Crazy"?', options: ['Jimin', 'V', 'J-Hope', 'RM'], answerIndex: 0, explanation: 'Jimin\'s "Like Crazy" reached number one in April 2023.', source: wiki('Like Crazy (Jimin song)') },
  { question: 'What is the name of the cartoon characters BTS created with LINE Friends?', options: ['BT21', 'Bangtan Bombs', 'TinyTAN', 'BTSverse'], answerIndex: 0, explanation: 'BT21 launched in 2017, with each member designing a character.', source: wiki('BT21') },
  { question: 'Map of the Soul: 7 was released in which year?', options: ['2018', '2019', '2020', '2021'], answerIndex: 2, explanation: 'Map of the Soul: 7 came out in February 2020, led by "On".', source: wiki('Map of the Soul: 7') },
]

const charliePuth: Q[] = [
  { question: 'What was Charlie Puth\'s debut single?', options: ['"Marvin Gaye"', '"One Call Away"', '"See You Again"', '"Attention"'], answerIndex: 0, explanation: '"Marvin Gaye" (2015) was his debut single.', source: wiki('Marvin Gaye (song)') },
  { question: 'Who sings with Charlie Puth on "Marvin Gaye"?', options: ['Meghan Trainor', 'Selena Gomez', 'Kehlani', 'Ariana Grande'], answerIndex: 0, explanation: '"Marvin Gaye" is a duet with Meghan Trainor.', source: wiki('Marvin Gaye (song)') },
  { question: '"See You Again" was written for which film?', options: ['Furious 7', 'Fast Five', 'The Fate of the Furious', 'Fast & Furious 6'], answerIndex: 0, explanation: 'It was written for Furious 7 (2015).', source: wiki('See You Again') },
  { question: 'Which rapper performs "See You Again" with Charlie Puth?', options: ['Wiz Khalifa', 'Drake', 'Post Malone', 'Kendrick Lamar'], answerIndex: 0, explanation: '"See You Again" is credited to Wiz Khalifa featuring Charlie Puth.', source: wiki('See You Again') },
  { question: 'How many weeks did "See You Again" spend at number one on the Billboard Hot 100?', options: ['4', '8', '12', '16'], answerIndex: 2, explanation: 'It spent 12 weeks at number one.', source: wiki('See You Again') },
  { question: '"See You Again" was written as a tribute to which actor?', options: ['Paul Walker', 'Vin Diesel', 'Heath Ledger', 'Philip Seymour Hoffman'], answerIndex: 0, explanation: 'It honoured Paul Walker, who died during the making of Furious 7.', source: wiki('See You Again') },
  { question: 'What is the name of Charlie Puth\'s debut album?', options: ['Nine Track Mind', 'Voicenotes', 'Charlie', 'Attention'], answerIndex: 0, explanation: 'Nine Track Mind came out in January 2016.', source: wiki('Nine Track Mind') },
  { question: 'In which year was Nine Track Mind released?', options: ['2014', '2016', '2018', '2020'], answerIndex: 1, explanation: 'Nine Track Mind was released in January 2016.', source: wiki('Nine Track Mind') },
  { question: '"Attention" was the lead single from which album?', options: ['Voicenotes', 'Nine Track Mind', 'Charlie', 'Some Type of Love'], answerIndex: 0, explanation: '"Attention" (2017) led his second album, Voicenotes.', source: wiki('Attention (Charlie Puth song)') },
  { question: 'In which year was Voicenotes released?', options: ['2016', '2017', '2018', '2019'], answerIndex: 2, explanation: 'Voicenotes came out in May 2018.', source: wiki('Voicenotes') },
  { question: 'What is the title of Charlie Puth\'s third album?', options: ['Charlie', 'Puth', 'Light Switch', 'Left and Right'], answerIndex: 0, explanation: 'His third album, Charlie, came out in 2022.', source: wiki('Charlie (Charlie Puth album)') },
  { question: 'Charlie Puth is known for having which musical ability?', options: ['Perfect (absolute) pitch', 'A seven-octave range', 'Playing ten instruments live', 'Synaesthesia'], answerIndex: 0, explanation: 'He has perfect pitch and often names the notes of everyday sounds.', source: wiki('Charlie Puth') },
  { question: 'Which music college did Charlie Puth graduate from?', options: ['Berklee College of Music', 'Juilliard', 'Royal Academy of Music', 'Curtis Institute'], answerIndex: 0, explanation: 'He graduated from Berklee in 2013.', source: wiki('Charlie Puth') },
  { question: 'Charlie Puth grew up in which US state?', options: ['New Jersey', 'California', 'Texas', 'Florida'], answerIndex: 0, explanation: 'He grew up in Rumson, New Jersey.', source: wiki('Charlie Puth') },
  { question: 'Which talk-show host signed Charlie Puth to her record label?', options: ['Ellen DeGeneres', 'Oprah Winfrey', 'Kelly Clarkson', 'Drew Barrymore'], answerIndex: 0, explanation: 'Ellen DeGeneres signed him to her label eleveneleven in 2011 after his YouTube covers.', source: wiki('Charlie Puth') },
  { question: 'What was the name of Ellen DeGeneres\'s record label that signed Charlie Puth?', options: ['eleveneleven', 'OneTwoThree', 'Daybreak', 'Rumson Records'], answerIndex: 0, explanation: 'He was signed to eleveneleven in 2011.', source: wiki('Charlie Puth') },
  { question: 'Who features on "We Don\'t Talk Anymore"?', options: ['Selena Gomez', 'Meghan Trainor', 'Kehlani', 'Dua Lipa'], answerIndex: 0, explanation: '"We Don\'t Talk Anymore" (2016) features Selena Gomez.', source: wiki("We Don't Talk Anymore (Charlie Puth song)") },
  { question: '"One Call Away" is from which album?', options: ['Nine Track Mind', 'Voicenotes', 'Charlie', 'Furious 7 soundtrack'], answerIndex: 0, explanation: '"One Call Away" (2015) is on Nine Track Mind.', source: wiki('One Call Away (Charlie Puth song)') },
  { question: '"How Long" is from which album?', options: ['Voicenotes', 'Nine Track Mind', 'Charlie', 'Some Type of Love'], answerIndex: 0, explanation: '"How Long" (2017) was the second single from Voicenotes.', source: wiki('How Long (Charlie Puth song)') },
  { question: '"Light Switch" is from which album?', options: ['Charlie', 'Voicenotes', 'Nine Track Mind', 'Attention'], answerIndex: 0, explanation: '"Light Switch" (2022) is on Charlie.', source: wiki('Light Switch (song)') },
  { question: 'Who features on Charlie Puth\'s "Left and Right"?', options: ['Jungkook of BTS', 'Jimin of BTS', 'Shawn Mendes', 'Harry Styles'], answerIndex: 0, explanation: '"Left and Right" (2022) features Jungkook, linking two QuickSeat headliners.', source: wiki('Left and Right (Charlie Puth song)') },
  { question: 'On which platform did Charlie Puth build many songs from Charlie in public?', options: ['TikTok', 'Twitch', 'Instagram Live', 'SoundCloud'], answerIndex: 0, explanation: 'He shared songwriting videos on TikTok while making the album.', source: wiki('Charlie (Charlie Puth album)') },
  { question: 'Who features on "Done for Me"?', options: ['Kehlani', 'Selena Gomez', 'Meghan Trainor', 'Halsey'], answerIndex: 0, explanation: '"Done for Me" (2018) features Kehlani.', source: wiki('Done for Me') },
  { question: 'Which instrument is Charlie Puth best known for playing?', options: ['Piano', 'Guitar', 'Drums', 'Saxophone'], answerIndex: 0, explanation: 'He is a pianist and often writes at the keyboard.', source: wiki('Charlie Puth') },
  { question: '"See You Again" was nominated for which major Grammy?', options: ['Song of the Year', 'Album of the Year', 'Best New Artist', 'Best Rap Album'], answerIndex: 0, explanation: 'It was nominated for Song of the Year at the 2016 Grammys.', source: wiki('58th Annual Grammy Awards') },
  { question: 'In 2017 the "See You Again" video overtook which video as YouTube\'s most viewed?', options: ['"Gangnam Style"', '"Despacito"', '"Baby Shark"', '"Shape of You"'], answerIndex: 0, explanation: 'It passed "Gangnam Style" in July 2017.', source: wiki('See You Again') },
  { question: 'Which record label releases Charlie Puth\'s albums?', options: ['Atlantic Records', 'Columbia Records', 'Interscope', 'Republic Records'], answerIndex: 0, explanation: 'His albums are released through Atlantic Records.', source: wiki('Charlie Puth') },
  { question: 'In which year was "Girlfriend" released?', options: ['2017', '2019', '2021', '2023'], answerIndex: 1, explanation: '"Girlfriend" came out in 2019.', source: wiki('Charlie Puth discography') }, // VERIFY
  { question: 'What chart peak did "Attention" reach on the Billboard Hot 100?', options: ['Top 5', 'Number one', 'Top 40 only', 'It didn\'t chart'], answerIndex: 0, explanation: '"Attention" peaked at number five.', source: wiki('Attention (Charlie Puth song)') }, // VERIFY
  { question: 'Which artist did Charlie Puth team up with on "Hard on Yourself"?', options: ['blackbear', 'Lauv', 'Jason Derulo', 'Shawn Mendes'], answerIndex: 0, explanation: '"Hard on Yourself" (2020) is a collaboration with blackbear.', source: wiki('Charlie Puth discography') }, // VERIFY
  { question: 'In which year was the album Charlie released?', options: ['2020', '2021', '2022', '2023'], answerIndex: 2, explanation: 'Charlie came out in October 2022.', source: wiki('Charlie (Charlie Puth album)') },
]

const build = (artistId: ArtistId, list: Q[]): TriviaQuestion[] =>
  list.map((q, i) => ({ ...q, artistId, id: `${artistId}-${String(i + 1).padStart(2, '0')}` }))

export const triviaBank: Record<ArtistId, TriviaQuestion[]> = {
  'taylor-swift': build('taylor-swift', taylorSwift),
  bts: build('bts', bts),
  'charlie-puth': build('charlie-puth', charliePuth),
}

export const findQuestion = (id: string) => Object.values(triviaBank).flat().find((q) => q.id === id)
